### ISSUE TITLE
Reprojection Yandex Sat 

### ISSUE THREAD

**Issue by gellerroman** [gunyakov/maptorium-server#1]
Yandex Sat have a epsg 3395, but almost maps have epsg:3857 projection.
So this maps dont consistency.
Is it in list TO DO fix?

**Comment by gunyakov** [comment]
I haven't used Yandex maps. But I'll see what can be done there.

**Comment by gunyakov** [comment]
I check your request. This is not related to server side and related only for UI. Server side properly store tiles for this map. Ability to adjust tiles projection based only on ability of leaflet to make this adjustments. But if you use Yandex sat + Yandex Hybrid overlay, its no any problems to display map. Problem become only if you try to use Google Sat and Yandex Overlay. I will close this issue. But if you still need it, pls open new in maptorium-leaflet repo.
